---
- name: Install Nexus
  hosts: "all"
  remote_user: root
  vars:
    nexus_version: 3.37.0
    nexus_download_url: https://download.sonatype.com/nexus/3/nexus-3.37.1-01-unix.tar.gz
    nexus_download_dest: /tmp/nexus-{{nexus_version}}
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /usr/local/nexus
  
  tasks:

    - name: create "nexus" group
      group: name=nexus 

    - name: create "nexus" user
      user: name=nexus group=nexus 

    - name: Install wget
      yum: name=wget state=installed

#    - name: Download Nexus
#      get_url: url="{{ nexus_download_url }}" dest={{ nexus_download_dest }} 
#      become: false
#      register: nexus_download

    - name: wget nexus
      command: wget {{ nexus_download_url }} -P {{ nexus_download_dest }}

    - name: create {{nexus_extracted_dir}} directory
      file: path={{nexus_extracted_dir}} state=directory
#      when: nexus_download.changed

    - name: extract nexus to {{nexus_extracted_dir}}
      command: tar xzf {{ nexus_download_dest }}/nexus-3.37.1-01-unix.tar.gz -C {{ nexus_extracted_dir }} --strip-components=1
#      when: nexus_download.changed

    - name: move nexus to {{nexus_dir}} directory
      command: cp -a {{nexus_extracted_dir}}/. {{nexus_dir}}
#      when: nexus_download.changed

    - name: remove {{nexus_extracted_dir}} directory
      command: rm -rf {{nexus_extracted_dir}}
#      when: nexus_download.changed

    - name: make {{nexus_dir}} directory property of "nexus" user/group
      file: path={{nexus_dir}} group=nexus owner=nexus recurse=true

    - name: make nexus runned by "nexus" user
      lineinfile: dest={{ nexus_dir }}/bin/nexus regexp="#RUN_AS_USER=" line="RUN_AS_USER=nexus" backrefs=true

    - name: set NEXUS_HOME
      lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{nexus_dir}}" backrefs=true

    - name: create nexus piddir
      file: path=/var/run/nexus state=directory group=nexus owner=nexus

    - name: set nexus pidir
      lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true

#    - name: create symbolic links to /etc/init.d/nexus
#      file: src={{nexus_dir}}/bin/nexus dest=/etc/init.d/nexus state=link

    - name: set nexus working directory
      lineinfile: dest={{nexus_dir}}/etc/nexus-default.properties regexp="^nexus-work=" line="nexus-work=${bundleBasedir}/work/nexus"

    - name: Nexus up
      command: ./nexus start
      args:
        chdir: /usr/local/nexus/bin

#    - name: Nexus up
#      service:
#        name: nexus
#        state: started
#        enabled: true