---
- name: Tailscale
  hosts: "all"
  remote_user: root
  vars:
    yum_dependencies:
      - yum-utils
      - gnupg2
    distribucion:
      - CentOS

    yum_repos:
      CentOS: https://pkgs.tailscale.com/stable/centos/7/tailscale.repo

    tailscale_package: tailscale 
    tailscale_service: tailscaled
    tailscale_auth_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66343066623965313335373839346662366362646665366132346662376234303136323634306534
          3865343032363637656333366139353231663435353763390a343434326338663831343161353436
          32356465653939323434376132313266383539356364383663643961616562646366376437666336
          6166333564363561660a303436326635633662343631313831353631396536356139653333633634
          64666231323035626364656665316562633633646633306561326535616536373138333565633638
          6561663630393463326131333932303439393764613963323737

    
  tasks:

    - name: Yum Dependencies
      become: true
      yum:
        name: "{{ yum_dependencies }}"
        state: present

    - name: Add Yum Repo
      become: true
      command: yum-config-manager --add-repo https://pkgs.tailscale.com/stable/centos/7/tailscale.repo
      args:
        creates: /etc/yum.repos.d/tailscale.repo

    - name: Install Tailscale
      become: true
      yum:
        name: "tailscale"
        disable_gpg_check: true
        state: latest

    - name: Tailscale up
      become: true
      service:
        name: "{{ tailscale_service }}"
        state: started
        enabled: true

    - name: Check if Tailscale is connected
      command: tailscale status & tailscale ip
      changed_when: false
      register: tailscale_status
      failed_when:
        - tailscale_status.rc != 0
        - "'Logged out.' not in tailscale_status.stdout"

    - name: Tailscale Status
      debug:
        var: tailscale_status 
    
    - name: Tailscale Up
      become: true
      command: tailscale up --authkey={{ tailscale_auth_key }} {{ tailscale_args | default() }}
      register: tailscale_start
      async: 60
      poll: 5 
    
    - name: Tailscale IP
      command: tailscale ip -4
      changed_when: false
      register: tailscale_ip 

